orders/urls.py
from django.conf.urls import handler404
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, reverse_lazy

from orders.views import (
    ResetPasswordView, RegisterView, IndexView, WishlistView, UserNotificationView, UserPaymentMethodView,
    UserSettingsView, UserAddressView, UserOrderView, CartView, ProductListView, ProductDetailView, ProductCommentView
)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login', LoginView.as_view(
        template_name='orders/auth/login.html',
        next_page=reverse_lazy('index')
    ), name='login'),
    path('logout', LogoutView.as_view(
        template_name='orders/auth/logout.html',
        next_page=reverse_lazy('index')
    ), name='logout'),
    path('register', RegisterView.as_view(), name='register'),
    path('reset-password', ResetPasswordView.as_view(), name='reset_password'),

    path('wishlist', WishlistView.as_view(), name='wishlist'),
    path('cart', CartView.as_view(), name='cart'),
    path('product/list', ProductListView.as_view(), name='product_list'),
    path('product/detail/<str:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('product/comment/<str:product_slug>', ProductCommentView.as_view(), name='add_product_comment'),
    path('user/payment-method', UserPaymentMethodView.as_view(), name='user_payment_method'),
    path('user/orders', UserOrderView.as_view(), name='user_orders'),
    path('user/notification', UserNotificationView.as_view(), name='user_notification'),
    path('user/address', UserAddressView.as_view(), name='user_address'),
    path('user/settings', UserSettingsView.as_view(), name='user_settings'),
    # path('404', ErrorNotFoundView.as_view(), name='error_404'),
]

handler404 = 'orders.views.error_page'

root/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include

from root import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models/product.py
from ckeditor.fields import RichTextField
from django.db.models import Model, ForeignKey, CASCADE, CharField, SlugField, DateTimeField, DecimalField, \
    SmallIntegerField, JSONField, TextField
from django.utils.text import slugify


def upload_directory_name(instance, filename):
    return f'products/{instance.product.id}/{filename}'


class Product(Model):
    name = CharField(max_length=255)
    slug = SlugField(max_length=255, unique=True, blank=True)
    price = DecimalField(decimal_places=2, max_digits=9)
    category = ForeignKey('orders.Category', CASCADE)
    promo_code = CharField(max_length=55)
    detail = RichTextField()
    quantity = SmallIntegerField(default=1)
    discount = SmallIntegerField(default=0)
    information = JSONField(default=dict)
    updated_at = DateTimeField(auto_now=True)
    created_at = DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

    def stock(self):
        return 'In Stock' if self.quantity > 0 else 'Out of Stock'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        i = Product.objects.filter(slug=self.slug).count()
        while Product.objects.filter(slug=self.slug).exists():
            self.slug += f'{i}'

        super().save(force_insert, force_update, using, update_fields)

orders/models/product_handbook.py
from django.db.models import Model, ForeignKey, CASCADE, CharField, SlugField, ImageField, SmallIntegerField, TextField, \
    DateTimeField
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey

from orders.models import upload_directory_name


class Category(MPTTModel):
    name = CharField(max_length=255)
    parent = TreeForeignKey('self', CASCADE, 'children', null=True, blank=True, )
    slug = SlugField(max_length=255, unique=True, blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return f'{self.name}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        i = Category.objects.filter(slug=self.slug).count()
        while Category.objects.filter(slug=self.slug).exists():
            self.slug += f'{i}'

        super().save(force_insert, force_update, using, update_fields)


class ProductImages(Model):
    product = ForeignKey('orders.Product', CASCADE)
    image = ImageField(upload_to=upload_directory_name)

    def __str__(self):
        return f'{self.product.name} -> {self.image.name}'


class Cart(Model):
    product = ForeignKey('orders.Product', CASCADE)
    user = ForeignKey('users.User', CASCADE)
    quantity = SmallIntegerField(default=1)

    @property
    def total_price(self):
        return sum(self.user.cart_set.values_list('product__price', flat=True))


class Comment(Model):
    product = ForeignKey('orders.Product', CASCADE)
    headline = CharField(max_length=255)
    text = TextField()
    author = ForeignKey('users.User', CASCADE)
    rate = SmallIntegerField(default=0)
    updated_at = DateTimeField(auto_now=True)
    created_at = DateTimeField(auto_now_add=True)


class CommentImage(Model):
    product = ForeignKey('orders.Comment', CASCADE)
    picture = ImageField(upload_to='comments/')

orders/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import CharField, EmailField, ModelForm, IntegerField

from orders.models import Comment, Product


class CustomUserCreationForm(UserCreationForm):
    first_name = CharField(max_length=255)
    last_name = CharField(max_length=255)
    email = EmailField(max_length=255)


class UserSettingsForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class CommentModelForm(ModelForm):

    class Meta:
        model = Comment
        exclude = ('created_at', 'updated_at', 'author')

orders/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, ListView, DetailView, UpdateView
from django_filters import FilterSet
from django_filters.views import FilterMixin

from orders.forms import CustomUserCreationForm, UserSettingsForm, CommentModelForm
from orders.models import Product, Cart


def error_page(request, error):
    render(request, '404.html', status=404)


class IndexView(TemplateView):
    template_name = 'orders/index.html'


class ResetPasswordView(TemplateView):
    template_name = 'orders/auth/reset-password.html'


class WishlistView(TemplateView):
    template_name = 'orders/products/wishlist.html'


class CartView(ListView):
    queryset = Cart.objects.all()
    template_name = 'orders/products/cart.html'
    context_object_name = 'cart'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user).first


class ProductListView(ListView):
    queryset = Product.objects.order_by('-created_at')
    template_name = 'orders/products/list.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset()
        slug = self.request.GET.get('slug', None)
        if slug:
            qs = qs.filter(category__slug=slug)
        return qs


class ProductDetailView(DetailView):
    queryset = Product.objects.order_by('-created_at')
    template_name = 'orders/products/detail.html'
    context_object_name = 'product'


class RegisterView(FormView):
    form_class = CustomUserCreationForm
    template_name = 'orders/auth/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductCommentView(FormView):
    form_class = CommentModelForm
    template_name = 'orders/products/detail.html'

    def post(self, request, *args, **kwargs):
        form = CommentModelForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()


        return redirect('product_detail', kwargs.get('product_slug'))


class UserNotificationView(TemplateView):
    template_name = 'orders/account/notification.html'


class UserOrderView(TemplateView):
    template_name = 'orders/account/orders.html'


class UserPaymentMethodView(TemplateView):
    template_name = 'orders/account/payment-method.html'


class UserAddressView(TemplateView):
    template_name = 'orders/account/address.html'


class UserSettingsView(FormView):
    template_name = 'orders/account/settings.html'
    form_class = UserSettingsForm
    success_url = reverse_lazy('user_settings')

    def form_valid(self, form):
        User.objects.filter(pk=self.request.user.id).update(**form.cleaned_data)
        return super().form_valid(form)

templates/orders/products/cart.html
{% extends 'orders/base.html' %}
{% load static %}

{% block title %}
    Cart Page
{% endblock %}

{% block main_content %}
    <div class="mt-4">
        <div class="container">
            <!-- row -->
            <div class="row ">
                <!-- col -->
                <div class="col-12">
                    <!-- breadcrumb -->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-0">
                            <li class="breadcrumb-item"><a href="#!">Home</a></li>
                            <li class="breadcrumb-item"><a href="#!">Shop</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Shop Cart</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <section class="mb-lg-14 mb-8 mt-8">
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-12">
                    <!-- card -->
                    <div class="card py-1 border-0 mb-8">
                        <div>
                            <h1 class="fw-bold">Shop Cart</h1>
                            <p class="mb-0">Shopping in 382480</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- row -->
            <div class="row">
                <div class="col-lg-8 col-md-7">

                    <div class="py-3">
                        {#                        <!-- alert -->#}
                        {#                        <div class="alert alert-danger p-2" role="alert">#}
                        {#                            You’ve got FREE delivery. Start <a href="#!" class="alert-link">checkout now!</a>#}
                        {#                        </div>#}
                        <ul class="list-group list-group-flush">
                            {% for cart in user.cart_set.all %}
                                <li class="list-group-item py-3 py-lg-0 px-0 {% if forloop.first %}border-top{% endif %} {% if forloop.last %}border-bottom{% endif %}">
                                    <!-- row -->
                                    <div class="row align-items-center">
                                        <div class="col-3 col-md-2">
                                            <img src="{{ cart.product.productimages_set.first.image.url }}" alt="Ecommerce" class="img-fluid">
                                        </div>
                                        <div class="col-4 col-md-5">
                                            <!-- title -->
                                            <a href="{% url 'product_detail' cart.product.slug %}" class="text-inherit">
                                                <h6 class="mb-0">
                                                    {{ cart.product.name }}
                                                </h6></a>
                                            <span><small class="text-muted">.98 / lb</small></span>
                                            <!-- text -->
                                            <div class="mt-2 small lh-1">
                                                <a href="#!" class="text-decoration-none text-inherit">
                                                    <span class="me-1 align-text-bottom">
                          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none"
                               stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                               class="feather feather-trash-2 text-success">
                            <polyline points="3 6 5 6 21 6"></polyline>
                            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                            </path>
                            <line x1="10" y1="11" x2="10" y2="17"></line>
                            <line x1="14" y1="11" x2="14" y2="17"></line>
                          </svg></span><span class="text-muted">Remove</span></a></div>
                                        </div>
                                        <!-- input group -->
                                        <div class="col-3 col-md-3 col-lg-2">
                                            <!-- input -->
                                            <div class="input-group input-spinner  ">
                                                <input type="button" value="-" class="button-minus  btn  btn-sm "
                                                       data-field="quantity">
                                                <input type="number" step="1" max="10" value="1" name="quantity"
                                                       class="quantity-field form-control-sm form-input   ">
                                                <input type="button" value="+" class="button-plus btn btn-sm "
                                                       data-field="quantity">
                                            </div>


                                        </div>
                                        <!-- price -->
                                        <div class="col-2 text-lg-end text-start text-md-end col-md-2">
                                            <span class="fw-bold">${{ cart.product.price }}</span>

                                        </div>
                                    </div>

                                </li>
                            {% endfor %}
                        </ul>
                        <!-- btn -->
                        <div class="d-flex justify-content-between mt-4">
                            <a href="#!" class="btn btn-primary">Continue Shopping</a>
                            <a href="#!" class="btn btn-dark">Update Cart</a>
                        </div>

                    </div>
                </div>

                <!-- sidebar -->
                <div class="col-12 col-lg-4 col-md-5">
                    <!-- card -->
                    <div class="mb-5 card mt-6">
                        <div class="card-body p-6">
                            <!-- heading -->
                            <h2 class="h5 mb-4">Summary</h2>
                            <div class="card mb-2">
                                <!-- list group -->
                                <ul class="list-group list-group-flush">
                                    <!-- list group item -->
                                    <li class="list-group-item d-flex justify-content-between align-items-start">
                                        <div class="me-auto">
                                            <div>Item Subtotal</div>

                                        </div>
                                        <span>$70.00</span>
                                    </li>

                                    <!-- list group item -->
                                    <li class="list-group-item d-flex justify-content-between align-items-start">
                                        <div class="me-auto">
                                            <div>Service Fee</div>

                                        </div>
                                        <span>$3.00</span>
                                    </li>
                                    <!-- list group item -->
                                    <li class="list-group-item d-flex justify-content-between align-items-start">
                                        <div class="me-auto">
                                            <div class="fw-bold">Subtotal</div>

                                        </div>
                                        <span class="fw-bold">$67.00</span>
                                    </li>
                                </ul>

                            </div>
                            <div class="d-grid mb-1 mt-4">
                                <!-- btn -->
                                <button class="btn btn-primary btn-lg d-flex justify-content-between align-items-center"
                                        type="submit">
                                    Go to Checkout <span class="fw-bold">${{ cart.total_price }}</span></button>
                            </div>
                            <!-- text -->
                            <p><small>By placing your order, you agree to be bound by the Freshcart <a href="#!">Terms
                                of Service</a>
                                and <a href="#!">Privacy Policy.</a> </small></p>

                            <!-- heading -->
                            <div class="mt-8">
                                <h2 class="h5 mb-3">Add Promo or Gift Card</h2>
                                <form>
                                    <div class="mb-2">
                                        <!-- input -->
                                        <label for="giftcard" class="form-label sr-only">Email address</label>
                                        <input type="text" class="form-control" id="giftcard"
                                               placeholder="Promo or Gift Card">

                                    </div>
                                    <!-- btn -->
                                    <div class="d-grid">
                                        <button type="submit" class="btn btn-outline-dark mb-1">Redeem</button>
                                    </div>
                                    <p class="text-muted mb-0"><small>Terms &amp; Conditions apply</small></p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}